### PR TITLE
small change to update output json

### PR DESCRIPTION
**Pull request by sainitishkumar**
#59

### CODE REVIEW

**Comment by dr5hn** [comment]
@sainitishkumar Thanks for fixing the bug.

**Comment by dr5hn** [comment]
@sainitishkumar Did you validated that if it's not creating a loop? Since i've attached an event on update of output.

**Comment by sainitishkumar** [comment]
Since I am not calling the handleChange function again, I think it wouldn't create a loop

**Comment by dr5hn** [comment]
Tested. LGTM 👍🏼

**Review by dr5hn — APPROVED** [review]

**Pull request merged**
